export const ADD_QUESTION = 'ADD_QUESTION'
export const REMOVE_QUESTION = 'REMOVE_QUESTION'
export const SELECTED_QUESTION = 'SELECTED_QUESTION'
export const REMOVE_SELECTED_QUESTION = 'REMOVE_SELECTED_QUESTION'
export const EDIT_QUESTION = 'EDIT_QUESTION'
export const SET_QUIZ_QUESTIONS = 'SET_QUIZ_QUESTIONS'
export const SAVE_QUESTIONS_TO_LOCAL = 'SAVE_QUESTIONS_TO_LOCAL'

export const SET_PLAYER_NAME = 'SET_PLAYER_NAME'

export const ADD_RESULT = 'ADD_RESULT'
export const CLEAR_LEADERBOARD = 'CLEAR_LEADERBOARD'
export const SAVE_LEADERBOARD = 'SAVE_LEADERBOARD'